### ISSUE TITLE
Support for UAVs propelled by more than 4 rotors

### ISSUE THREAD

**Issue by RustyNorwell** [ctu-mrs/mrs_multirotor_simulator#1]
### Bug: Simulation crashes when running standalone_400_uavs session

**Description**
UAV params are not loaded properly during the initialization phase and the default ones (for x500) are used.
This causes segmentation fault, when using more than 4 rotor UAV, since the model was initialized for 4 rotors but tries to set motor input for 6 rotors thus reaching uninitialized memory (see MultirotorModel::setInput()).
 
**User Hotfix**
Use quadrotors.

**Comment by RustyNorwell** [comment]
Solved by initializing states (including vector of motors' inputs that caused the error) again after loading proper parameters of UAVs.

**Comment by klaxalk** [comment]
Thanks, fixed the in the system. Will be on stable PPA tomorow.
